function [PSI] = getPSI(K,theta,e)
% Sai Charan Malladi
% AE16B029 IIT Madras
% 2/1/2019
% Returns the PSI matrix per Eq. 2.46 in Sherrill's paper

% find psi's Eq. 2.47-2.49
psi1 = [sin(theta)*(1+e*cos(theta));...
        2*cos(theta)-e*(sin(theta))^2;...
        0;...
        cos(theta)+e*cos(2*theta);...
        -2*sin(theta)*(1+e*cos(theta));...
        0];
psi2 = [cos(theta)*(1+e*cos(theta));...
        -2*sin(theta)-e*sin(theta)*cos(theta);...
        0;...
        -sin(theta)-e*sin(2*theta);...
        e-2*cos(theta)*(1+e*cos(theta));...
        0];
psi3 = [1-3*e/2*K*sin(theta)*(1+e*cos(theta));...
        -3/2*K*(1+e*cos(theta))^2;...
        0;...
        -3*e/2*K*(cos(theta)+e*cos(2*theta))-(3*e*sin(theta))/(2*(1+e*cos(theta)));...
        3*e*K*sin(theta)*(1+e*cos(theta))-3/2;
        0];
psi4 = [0;1;0;0;0;0];
psi5 = [0;0;sin(theta);0;0;cos(theta)];
psi6 = [0;0;cos(theta);0;0;-sin(theta)];

% concatinate
PSI = [psi1,psi2,psi3,psi4,psi5,psi6];

end
